#Build stage
FROM node:24-alpine AS builder

WORKDIR /library-identity-consumer-builder

COPY ./package.json ./package-lock.json ./
COPY ./tsconfig.base.json ./
COPY ./shared/database ./shared/database
COPY ./jobs/library-identity-consumer ./jobs/library-identity-consumer

RUN npm ci && npm run build --workspace=@wxyc/database --workspace=@wxyc/library-identity-consumer

#Production stage
FROM node:24-alpine AS prod

WORKDIR /library-identity-consumer

COPY ./package* ./
COPY ./jobs/library-identity-consumer/package* ./jobs/library-identity-consumer/
COPY ./shared/database/package* ./shared/database/

RUN npm install --omit=dev

COPY --from=builder ./library-identity-consumer-builder/jobs/library-identity-consumer/dist ./jobs/library-identity-consumer/dist
COPY --from=builder ./library-identity-consumer-builder/shared/database/dist ./shared/database/dist

CMD ["npm", "start", "--workspace=@wxyc/library-identity-consumer"]
