FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install && \
    npm run clean && \
    npm run build:auth

FROM node:20-alpine AS prod
WORKDIR /app
COPY package* ./
RUN npm install --production
COPY --from=builder ./app/apps/auth/dist ./dist

EXPOSE 8082

CMD ["npm", "start:auth"]