version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: wxyc-traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - wxyc-network

  auth-service:
    image: wxyc_auth_service:latest
    container_name: wxyc-auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`api.wxyc.local`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=8787"
      - "traefik.docker.network=wxyc-network"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BETTER_AUTH_URL=http://api.wxyc.local/auth
      - FRONTEND_SOURCE=${FRONTEND_SOURCE}
    networks:
      - wxyc-network
    depends_on:
      - db

  backend-service:
    image: wxyc_backend_service:latest
    container_name: wxyc-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.wxyc.local`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.docker.network=wxyc-network"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AUTH_SERVICE_URL=http://auth-service:8787
    networks:
      - wxyc-network
    depends_on:
      - db
      - auth-service

  db:
    image: postgres:latest
    container_name: wxyc-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - wxyc-network

networks:
  wxyc-network:
    driver: bridge

volumes:
  pg-data:
