-- Primary and secondary dj used in test automation
-- Note: In production, users should be created via better-auth service
-- For test/dev environments, we create test users directly in the seed file

-- Create test users for test automation
-- These users are required for the test suite to function
INSERT INTO auth_user (id, name, email, email_verified, username, dj_name, real_name, created_at, updated_at, app_skin)
VALUES
  ('test-dj1-id-00000000000000000001', 'test_dj1', 'test_dj1@wxyc.org', true, 'test_dj1', 'Test dj1', 'Test DJ 1', NOW(), NOW(), 'modern-light'),
  ('test-dj2-id-00000000000000000002', 'test_dj2', 'test_dj2@wxyc.org', true, 'test_dj2', 'Test dj2', 'Test DJ 2', NOW(), NOW(), 'modern-light')
ON CONFLICT (id) DO NOTHING;

-- Create auth_account entries for test users (credential provider for username/password login)
-- Password: testpassword123 (scrypt hash generated by better-auth/crypto)
-- Hash generated with: import { hashPassword } from 'better-auth/crypto'; hashPassword('testpassword123')
INSERT INTO auth_account (id, user_id, account_id, provider_id, password, created_at, updated_at)
VALUES
  ('test-account-1-000000000000000001', 'test-dj1-id-00000000000000000001', 'test_dj1', 'credential', '658683f3d57f62fc4140eff6bd79a1a7:3ccb6966bf4629a27bfb0be5471041dff9c751ad2513037f786a79c2fbdf455526f2c1e5d3d3acdabed3c4eb3506ec5312b1f19f3d22a5471e4c9bf8086fdd88', NOW(), NOW()),
  ('test-account-2-000000000000000002', 'test-dj2-id-00000000000000000002', 'test_dj2', 'credential', '29fd75d5d2ed6cc337f95d4e5b45e714:cf7d90a2b3a03a4b734f28c90faf6be08fedf051db646564adf3bb8befe2b5566fe2db3d052c9db9279a6985e821dfe3bc202dec2198f849374bd012e1013b6f', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Genres, media formats, artists, and albums used in test automation
INSERT INTO wxyc_schema.genres(genre_name) VALUES ('Rock');
INSERT INTO wxyc_schema.genres(genre_name) VALUES ('Hiphop');

INSERT INTO wxyc_schema.format(format_name) VALUES ('cd');
INSERT INTO wxyc_schema.format(format_name) VALUES ('vinyl');

INSERT INTO wxyc_schema.artists(
	artist_name, code_letters, code_artist_number, genre_id)
	VALUES ('Built to Spill', 'BU', 60, 1);

INSERT INTO wxyc_schema.artists(
	artist_name, code_letters, code_artist_number, genre_id)
	VALUES ('Ravyn Lenae', 'LE', 35, 2);

INSERT INTO wxyc_schema.artists(
	artist_name, code_letters, code_artist_number, genre_id)
	VALUES ('Jockstrap', 'JO', 108, 1);

INSERT INTO wxyc_schema.library(
    artist_id, genre_id, format_id, album_title, code_number) 
    VALUES (1, 1, 1, 'Keep it Like a Secret', 8);

INSERT INTO wxyc_schema.library(
    artist_id, genre_id, format_id, album_title, code_number) 
    VALUES (2, 2, 1, 'Crush', 1);

INSERT INTO wxyc_schema.library(
    artist_id, genre_id, format_id, album_title, code_number) 
    VALUES (3, 1, 2, 'I Love You Jennifer B', 1);

INSERT INTO wxyc_schema.rotation(album_id, play_freq) VALUES (1, 'L')