-- precondition-guard: not-required (no constraint added; CREATE FUNCTION
--   and CREATE INDEX IF NOT EXISTS are evaluated against existing data
--   only insofar as the index build reads every row, and the index
--   expression is total — `normalize_artist_name(input text)` coerces
--   NULL to '' via coalesce, so a NULL artist_name cannot raise.
--   No existing-row invariant is added.)
-- @no-precondition-needed: no constraint is added. The function is
--   IMMUTABLE PARALLEL SAFE total over `text` and the indexes are
--   plain btree on the function's output — neither admits a data
--   invariant that current rows must satisfy.
-- @no-analyze-needed: no UPDATE in this migration. The CREATE INDEX
--   statements implicitly populate index stats during the build; the
--   underlying table row counts and column stats are unaffected.
--
-- 0092 — `normalize_artist_name(text)` SQL function + three functional
-- indexes supporting the concerts-artist-resolver job (BS#1372).
--
-- The resolver matches `concerts.headlining_artist_raw` against
-- `artists.artist_name` and `artist_search_alias.variant` after applying
-- a single canonical normalization: lowercase + strip a leading "The ".
-- That rule lives here as a SQL function (so the resolver's JOIN can
-- exploit a functional index instead of seq-scanning ~120k artists)
-- with a TypeScript twin at `shared/database/src/normalize-artist-name.ts`
-- (so iOS / dj-site / sibling resolvers normalize the same way).
--
-- The function is IMMUTABLE PARALLEL SAFE so Postgres can use it inside
-- functional indexes and parallelize index scans. `coalesce(input, '')`
-- makes the function total on NULL input — the indexes below depend on
-- this to avoid emitting NULL keys for rows whose `artist_name` is NULL.
--
-- Separator class: the regex `^the[ \t\n\r\f\v]+` uses an explicit POSIX
-- whitespace class instead of `\s`. PG ARE `\s` is ASCII-only; JS `\s`
-- matches the full Unicode whitespace class. The TS twin
-- (`shared/database/src/normalize-artist-name.ts`) uses the same explicit
-- class so the contract is byte-identical regardless of regex-engine
-- differences — NBSP / narrow no-break / U+2028 inputs are NOT stripped
-- by either side. The venue-events scraper already decodes `&nbsp;` to
-- ASCII space before this function runs, so the narrow class is fine in
-- practice.
--
-- Collation note: PG's `lower()` is catalog-marked IMMUTABLE but is
-- actually lc_ctype-dependent — the well-known foot-gun. The functional
-- indexes below freeze whatever lc_ctype the cluster has at build time.
-- WXYC RDS runs `en_US.UTF-8`; if that ever changes (or a restore
-- targets a different lc_ctype), REINDEX both functional indexes.
--
-- Index choices:
--
--   - `artists_normalized_name_idx` supports the strict-match arm. ~120k
--     artist rows; without the index the resolver would seq-scan per
--     concert. The index is non-unique because `artists.artist_name`
--     itself has ~235 duplicate groups (memory: `project_canonical_artists`)
--     — the resolver's "exactly one canonical match" guard is how those
--     stay NULL safely.
--
--   - `artist_search_alias_normalized_variant_idx` supports the alias
--     fallback arm. The existing `artist_search_alias_variant_trgm_idx`
--     (migration 0089) is a GIN trigram index optimized for substring
--     similarity, not equality on the normalized form; the alias arm
--     here is an equality predicate, so it needs its own btree.
--
--   - `concerts_headlining_artist_id_null_idx` is a partial COVERING
--     index on `concerts (id) INCLUDE (headlining_artist_raw)
--     WHERE headlining_artist_id IS NULL`. The recurring drain
--     (cron at "15 5 * * *") runs
--       SELECT id, headlining_artist_raw FROM concerts
--       WHERE headlining_artist_id IS NULL ...
--     daily; the INCLUDE column lets PG serve the loader as an Index
--     Only Scan and avoid a heap fetch per match. Pattern mirrors
--     migration 0074's covering partial on flowsheet metadata-attempt.
--
-- Concurrency: per `docs/migrations.md`'s `if-not-exists-index` rule,
-- the runbook for prod is to first build the three indexes out-of-band
-- with `CREATE INDEX CONCURRENTLY` so the migration here is a no-op
-- against the running database. The IF NOT EXISTS clauses below allow
-- the migration to apply cleanly in either order. The function itself
-- (CREATE OR REPLACE FUNCTION) is metadata-only and acquires no row-
-- level lock; safe to ship in-band.
--
-- Production runbook for the indexes (each CREATE INDEX CONCURRENTLY
-- runs outside any transaction; the function ships in the migration):
--
--   CREATE INDEX CONCURRENTLY IF NOT EXISTS "artists_normalized_name_idx"
--     ON "wxyc_schema"."artists" (wxyc_schema.normalize_artist_name("artist_name"));
--
--   CREATE INDEX CONCURRENTLY IF NOT EXISTS "artist_search_alias_normalized_variant_idx"
--     ON "wxyc_schema"."artist_search_alias" (wxyc_schema.normalize_artist_name("variant"));
--
--   CREATE INDEX CONCURRENTLY IF NOT EXISTS "concerts_headlining_artist_id_null_idx"
--     ON "wxyc_schema"."concerts" ("id") INCLUDE ("headlining_artist_raw") WHERE "headlining_artist_id" IS NULL;
--
-- Companion job: jobs/concerts-artist-resolver/ (this PR).

CREATE OR REPLACE FUNCTION wxyc_schema.normalize_artist_name(input text) RETURNS text
  LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT lower(regexp_replace(coalesce(input, ''), '^the[ \t\n\r\f\v]+', '', 'i'));
$$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "artists_normalized_name_idx" ON "wxyc_schema"."artists" USING btree (wxyc_schema.normalize_artist_name("artist_name"));--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "artist_search_alias_normalized_variant_idx" ON "wxyc_schema"."artist_search_alias" USING btree (wxyc_schema.normalize_artist_name("variant"));--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "concerts_headlining_artist_id_null_idx" ON "wxyc_schema"."concerts" USING btree ("id") INCLUDE ("headlining_artist_raw") WHERE "headlining_artist_id" IS NULL;
