-- 0133 (BS#1895, Not-on-Discogs epic #1280 sub-issue 5): project
-- library.discogs_unavailable / discogs_unavailable_note /
-- last_discogs_recheck_at (columns landed in 0-something via BS#1281,
-- already merged) onto library_artist_view so the catalog-search read path
-- (library-search.service.ts, which queries the view directly rather than
-- library.service.ts's LIBRARY_VIEW_PROJECTION join) can serialize the flag
-- to clients. View recreate only -- no data movement, no lock beyond the
-- brief DROP/CREATE VIEW pair, no backfill required (the columns already
-- exist and are populated).
DROP VIEW "wxyc_schema"."library_artist_view";--> statement-breakpoint
CREATE VIEW "wxyc_schema"."library_artist_view" AS (select "wxyc_schema"."library"."id", "wxyc_schema"."artists"."code_letters", "wxyc_schema"."genre_artist_crossreference"."artist_genre_code", "wxyc_schema"."library"."code_number", "wxyc_schema"."artists"."artist_name", "wxyc_schema"."artists"."alphabetical_name", "wxyc_schema"."library"."album_title", "wxyc_schema"."format"."format_name", "wxyc_schema"."genres"."genre_name", "wxyc_schema"."rotation"."rotation_bin", "wxyc_schema"."library"."add_date", "wxyc_schema"."library"."label", "wxyc_schema"."library"."label_id", "wxyc_schema"."library"."on_streaming", "wxyc_schema"."library"."album_artist", "wxyc_schema"."library"."plays", "wxyc_schema"."library"."artwork_url", "wxyc_schema"."artists"."discogs_artist_id", "wxyc_schema"."artists"."musicbrainz_artist_id", "wxyc_schema"."artists"."wikidata_qid", "wxyc_schema"."artists"."spotify_artist_id", "wxyc_schema"."artists"."apple_music_artist_id", "wxyc_schema"."artists"."bandcamp_id", "wxyc_schema"."library"."artist_id", "wxyc_schema"."library"."discogs_unavailable", "wxyc_schema"."library"."discogs_unavailable_note", "wxyc_schema"."library"."last_discogs_recheck_at" from "wxyc_schema"."library" inner join "wxyc_schema"."artists" on "wxyc_schema"."artists"."id" = "wxyc_schema"."library"."artist_id" inner join "wxyc_schema"."format" on "wxyc_schema"."format"."id" = "wxyc_schema"."library"."format_id" inner join "wxyc_schema"."genres" on "wxyc_schema"."genres"."id" = "wxyc_schema"."library"."genre_id" inner join "wxyc_schema"."genre_artist_crossreference" on ("wxyc_schema"."genre_artist_crossreference"."artist_id" = "wxyc_schema"."library"."artist_id" and "wxyc_schema"."genre_artist_crossreference"."genre_id" = "wxyc_schema"."library"."genre_id") left join "wxyc_schema"."rotation" on "wxyc_schema"."rotation"."album_id" = "wxyc_schema"."library"."id" AND ("wxyc_schema"."rotation"."kill_date" > CURRENT_DATE OR "wxyc_schema"."rotation"."kill_date" IS NULL));