-- BS#2479. Swap migration 0164's `rotation_card_id_idx` for a non-partial
-- btree the canonical active-rotation predicate can actually use.
--
-- @intentional-create-revert: this migration DROPs 0164's
-- `rotation_card_id_idx` and CREATEs a differently-named, differently-shaped
-- replacement — not a net no-op. 0164's index was never usable by the
-- queries it was built for (see below), so this is a correction, not
-- reverted schema evolution.
--
-- 0164 built `rotation_card_id_idx` partial on `kill_date IS NULL`, stating
-- in its header that the index existed to serve "the cards listing's
-- per-card active count and the admin list's card filter." Those two
-- queries, and every other rotation read in this repo (`getRotationFromDB`,
-- the search projections, `deleteRotationCardFromDB`'s guard), actually
-- filter on the broader canonical predicate — `kill_date IS NULL OR
-- kill_date > CURRENT_DATE` (`rotationActiveSql()`, exported from
-- shared/database/src/schema.ts next to `rotation` itself) —
-- because a future-dated kill is still rotating: catalog search still
-- emits its `rotation_bin` and `card`, so its card must still count it as
-- active or `DELETE /library/rotation/cards/:id` would unfile a record DJs
-- are still routed to (`rotation.card_id` is `ON DELETE SET NULL`).
--
-- Postgres uses a partial index only when it can prove the query's WHERE
-- implies the index predicate, and `kill_date IS NULL OR kill_date >
-- CURRENT_DATE` does not imply `kill_date IS NULL` — so 0164's index was
-- never usable for the queries its own header named. It cannot be widened
-- in place either: `CURRENT_DATE` is STABLE, not IMMUTABLE, and Postgres
-- rejects a non-immutable expression in an index predicate outright.
--
-- Plain `(card_id)`, not a `(card_id, kill_date)` composite. The
-- load-bearing change is partial -> non-partial: with no usable index on
-- `card_id`, both consumers seq-scan all ~21.6k rotation rows on every
-- delete-guard check and every cards listing. Between the two non-partial
-- shapes the choice is minimalism, not a measured composite penalty —
-- measured on a throwaway PG 18.6 cluster against a synthetic fixture
-- matching this table's documented shape (21,566 rows, of which 313 active
-- and filed across 40 cards; the counts 0150/0165's headers cite):
--
--   1. Point lookup (`deleteRotationCardFromDB`'s guard — `card_id = $1
--      AND (kill_date IS NULL OR kill_date > CURRENT_DATE)`): plain gets a
--      Bitmap Heap Scan (5 buffers, 3 heap blocks, 0.018 ms); the
--      composite an Index Only Scan (3 buffers, 0 heap fetches, 0.006 ms).
--      Both effectively free; the composite marginally ahead.
--
--   2. Listing (`listRotationCardsFromDB`'s `rotation_cards LEFT JOIN
--      rotation ON card_id = rotation_cards.id AND (kill_date IS NULL OR
--      kill_date > CURRENT_DATE) GROUP BY rotation_cards.id`), under
--      enable_seqscan = off to expose the index path a larger table would
--      take: 18 buffers / 0.135 ms on the composite — nothing for the
--      plain shape to meaningfully beat.
--
-- Both shapes serve both queries at this scale; either would close this
-- migration's actual gap. Plain wins on size (168 kB vs 272 kB — each leaf
-- entry carries only `card_id`) and on being the minimal shape the queries
-- demonstrably need: `kill_date` earns its keep as a post-scan Filter over
-- the small per-card row set (~310 active of 21,566), not as a second key
-- column maintained on every rotation write. If the listing ever gains a
-- kill_date-ordered access pattern, or active-row cardinality grows an
-- order of magnitude, re-measure before widening — the composite's
-- index-only point lookup is the upside to weigh then.
--
-- Lock behavior. Both statements run inside the whole pending-migration
-- batch's single transaction (docs/migrations.md's `single-transaction-migrate`
-- rule), and Postgres holds every lock they take to that batch's COMMIT —
-- not just for these two statements' own runtime. `CREATE INDEX` (this
-- non-CONCURRENTLY form) takes a SHARE lock on `rotation`: from that
-- statement on, writes (INSERT/UPDATE/DELETE) of `rotation` block for the
-- rest of the batch; reads do not. `DROP INDEX` (also non-CONCURRENTLY)
-- takes an AccessExclusiveLock on the TABLE `rotation`, not merely on the
-- index being dropped: from that statement on, reads AND writes of
-- `rotation` block until the whole batch commits — the same rule 0164's
-- header states for its ADD COLUMN. The statements' own runtime is tiny
-- (the drop is metadata-only; the build is one scan-and-sort of ~21.6k
-- rows), but that bounds only when each lock is ACQUIRED, never how long
-- it is held — the hold is governed by everything that runs after them in
-- the same transaction, i.e. every other migration pending in the same
-- deploy.
--
-- CREATE runs before DROP so `card_id` is never left with zero covering
-- indexes at any point the transaction could be inspected from outside (it
-- can't be, since both statements are in the same transaction as every
-- other pending migration — but the ordering is the same discipline 0139
-- documents, and it is what the out-of-band runbook below needs to be safe
-- to run partially).
--
-- Neither statement is the CONCURRENTLY form, because migrations run inside
-- a transaction (`CREATE INDEX CONCURRENTLY` / `DROP INDEX CONCURRENTLY`
-- cannot run inside a transaction block) — same constraint as 0057, 0068,
-- 0070, 0074, 0078, 0080, 0139, 0144, 0148, 0153, 0154, 0163. If this
-- deploy lands mid-show, pre-build out of band first, in this order:
--   CREATE INDEX CONCURRENTLY IF NOT EXISTS "rotation_card_id_full_idx"
--     ON "wxyc_schema"."rotation" USING btree ("card_id");
--   DROP INDEX CONCURRENTLY IF EXISTS "wxyc_schema"."rotation_card_id_idx";
-- Neither takes an AccessExclusiveLock; no write pause. Create before drop so
-- `card_id` is never uncovered. `IF NOT EXISTS` / `IF EXISTS` make the
-- in-migration statements no-ops against a database where the out-of-band
-- swap already happened, while fresh dev and CI databases pick up both
-- statements on first migrate. Same shape as 0068, 0070, 0074, 0080, 0139,
-- 0144, 0148, 0153, 0154, 0163.
--
-- @no-precondition-needed: an index swap changes no data and adds no
-- constraint — nothing here can find a row that violates anything.

CREATE INDEX IF NOT EXISTS "rotation_card_id_full_idx" ON "wxyc_schema"."rotation" USING btree ("card_id");--> statement-breakpoint
DROP INDEX IF EXISTS "wxyc_schema"."rotation_card_id_idx";
