-- BS#2835 (epic BS#2828): expose `genre_artist_crossreference.code_comp_letter` on `library_artist_view`.
--
-- The call number's artist half is `artist_genre_code`, and for the 52 lettered Rock/Soundtracks compilation sections it is 0 for every section; the section letter (`code_comp_letter`, migration 0183) is what tells them apart. The view already joins `genre_artist_crossreference` on `(artist_id, genre_id)`, so the letter comes from the same row as `code_artist_number`.
--
-- DDL-only and additive: one column onto a view, no table touched, no data read or written. Every column of 0184's view is carried forward unchanged and in order (including `code_volume_letters`, which a view recreated from an older column list would silently drop); the new column sits beside `code_artist_number`. DROP + CREATE rather than CREATE OR REPLACE because CREATE OR REPLACE VIEW cannot insert a column anywhere but the end. Nothing depends on this view in the database, so the DROP needs no CASCADE, matching 0184.
--
-- No watermark-trigger change: `touch_library_watermark_from_gac` (0105) fires on any INSERT, UPDATE, DELETE or TRUNCATE of `genre_artist_crossreference`, with no `UPDATE OF` column list, so a write that sets only `code_comp_letter` already advances `library_watermark`.

DROP VIEW "wxyc_schema"."library_artist_view";--> statement-breakpoint
CREATE VIEW "wxyc_schema"."library_artist_view" AS (select "wxyc_schema"."library"."id", "wxyc_schema"."artists"."code_letters", "wxyc_schema"."genre_artist_crossreference"."artist_genre_code", "wxyc_schema"."genre_artist_crossreference"."code_comp_letter", "wxyc_schema"."library"."code_number", "wxyc_schema"."library"."code_volume_letters", "wxyc_schema"."artists"."artist_name", "wxyc_schema"."artists"."alphabetical_name", "wxyc_schema"."library"."album_title", "wxyc_schema"."format"."format_name", "wxyc_schema"."genres"."genre_name", "wxyc_schema"."library"."genre_id", "wxyc_schema"."rotation"."rotation_bin", "wxyc_schema"."library"."add_date", "wxyc_schema"."library"."label", "wxyc_schema"."library"."label_id", "wxyc_schema"."library"."on_streaming", "wxyc_schema"."library"."album_artist", "wxyc_schema"."library"."plays", "wxyc_schema"."library"."artwork_url", "wxyc_schema"."artists"."discogs_artist_id", "wxyc_schema"."artists"."musicbrainz_artist_id", "wxyc_schema"."artists"."wikidata_qid", "wxyc_schema"."artists"."spotify_artist_id", "wxyc_schema"."artists"."apple_music_artist_id", "wxyc_schema"."artists"."bandcamp_id", "wxyc_schema"."library"."artist_id", "wxyc_schema"."library"."discogs_unavailable", "wxyc_schema"."library"."discogs_unavailable_note", "wxyc_schema"."library"."last_discogs_recheck_at", "wxyc_schema"."rotation_cards"."id" as "rotation_card_id", "wxyc_schema"."rotation_cards"."bin", "wxyc_schema"."rotation_cards"."number", "wxyc_schema"."rotation_cards"."name" from "wxyc_schema"."library" inner join "wxyc_schema"."artists" on "wxyc_schema"."artists"."id" = "wxyc_schema"."library"."artist_id" inner join "wxyc_schema"."format" on "wxyc_schema"."format"."id" = "wxyc_schema"."library"."format_id" inner join "wxyc_schema"."genres" on "wxyc_schema"."genres"."id" = "wxyc_schema"."library"."genre_id" inner join "wxyc_schema"."genre_artist_crossreference" on ("wxyc_schema"."genre_artist_crossreference"."artist_id" = "wxyc_schema"."library"."artist_id" and "wxyc_schema"."genre_artist_crossreference"."genre_id" = "wxyc_schema"."library"."genre_id") left join "wxyc_schema"."rotation" on "wxyc_schema"."rotation"."album_id" = "wxyc_schema"."library"."id" AND ("wxyc_schema"."rotation"."kill_date" > CURRENT_DATE OR "wxyc_schema"."rotation"."kill_date" IS NULL) left join "wxyc_schema"."rotation_cards" on "wxyc_schema"."rotation_cards"."id" = "wxyc_schema"."rotation"."card_id");